Package python deps with dh-virtualenv
* bump debhelper and debian/compat to 9
* Pre-Depends

Build command of doom:

echo USENETWORK=yes >> /root/.pbuilderrc

dh-virtualenv 0.9 package from upstream.

DEB_BUILD_OPTIONS=nocheck git-buildpackage -nc \
    --git-pbuilder \
    --git-dist="precise-wikimedia" \
    --git-pbuilder-options="--bindmount /packaging/deps/precise"

Bug: T48552
Change-Id: I7eb60ed9ffbbb60140e1dcfd516db51732167ed0

diff --git a/debian/zuul-merger.init b/debian/zuul-merger.init
--- a/debian/zuul-merger.init
+++ b/debian/zuul-merger.init
@@ -13,9 +13,9 @@
 
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="Zuul"
-NAME=zuul
-DAEMON=/usr/bin/zuul-server
+DESC="Zuul Merger"
+NAME=zuul-merger
+DAEMON=/usr/bin/$NAME
 PIDFILE=/var/run/$NAME/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 USER=zuul
@@ -23,8 +23,7 @@ USER=zuul
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
 
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+START_DAEMON=1
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -32,6 +31,21 @@ USER=zuul
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
+
+# Read configuration variable file if it is present
+if [ -r /etc/default/$NAME ] ; then
+   . /etc/default/$NAME
+else
+	log_daemon_msg "$DESC: /etc/default/$NAME not found: exiting"
+	log_end_msg 1
+	exit 0
+fi
+
+if ! [ "${START_DAEMON}" = "1" ] ; then
+	log_daemon_msg "$DESC: /etc/default/$NAME is not set to START_DAEMON=1: exiting"
+	log_end_msg 1
+	exit 0
+fi
 
 #
 # Function that starts the daemon/service
@@ -43,8 +57,9 @@ do_start()
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
 
-        mkdir -p /var/run/$NAME
+	mkdir -p /var/run/$NAME
 	chown $USER /var/run/$NAME
+	ulimit -n 8192
 	start-stop-daemon --start --quiet --pidfile $PIDFILE -c $USER --exec $DAEMON --test > /dev/null \
 		|| return 1
 	start-stop-daemon --start --quiet --pidfile $PIDFILE -c $USER --exec $DAEMON -- \
@@ -73,31 +88,6 @@ do_stop()
 }
 
 #
-# Function that stops the daemon/service
-#
-do_graceful_stop()
-{
-	PID=`cat $PIDFILE`
-	kill -USR1 $PID
-
-	# wait until really stopped
-	if [ -n "${PID:-}" ]; then
-		i=0
-		while kill -0 "${PID:-}" 2> /dev/null;  do
-			if [ $i -eq '0' ]; then
-				echo -n " ... waiting "
-			else
-				echo -n "."
-			fi
-			i=$(($i+1))
-			sleep 1
-		done
-	fi
-
-	rm -f /var/run/$NAME/*
-}
-
-#
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
@@ -106,7 +96,7 @@ do_reload() {
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name zuul-server
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name zuul-merger
 	return 0
 }
 
@@ -145,7 +135,7 @@ case "$1" in
 	# 'force-reload' alias
 	#
 	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_graceful_stop
+	do_stop
 	do_start
 	;;
   *)
